// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ProxyV1Interface is an autogenerated mock type for the ProxyV1Interface type
type ProxyV1Interface struct {
	mock.Mock
}

type ProxyV1Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *ProxyV1Interface) EXPECT() *ProxyV1Interface_Expecter {
	return &ProxyV1Interface_Expecter{mock: &_m.Mock}
}

// Proxy provides a mock function with given fields: _a0, _a1
func (_m *ProxyV1Interface) Proxy(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// ProxyV1Interface_Proxy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Proxy'
type ProxyV1Interface_Proxy_Call struct {
	*mock.Call
}

// Proxy is a helper method to define mock.On call
//  - _a0 http.ResponseWriter
//  - _a1 *http.Request
func (_e *ProxyV1Interface_Expecter) Proxy(_a0 interface{}, _a1 interface{}) *ProxyV1Interface_Proxy_Call {
	return &ProxyV1Interface_Proxy_Call{Call: _e.mock.On("Proxy", _a0, _a1)}
}

func (_c *ProxyV1Interface_Proxy_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *ProxyV1Interface_Proxy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *ProxyV1Interface_Proxy_Call) Return() *ProxyV1Interface_Proxy_Call {
	_c.Call.Return()
	return _c
}
